import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useOrgContext } from "@/hooks/useOrgContext";
import { useNotification } from "@/hooks/useNotification";
import DashboardLayout from "@/components/Layout/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowLeft, ArrowRight, Check, Save } from "lucide-react";

export default function NewApplication() {
  const navigate = useNavigate();
  const { orgId } = useOrgContext();
  const notify = useNotification();
  const queryClient = useQueryClient();
  const [currentTab, setCurrentTab] = useState("basic");

  // Form state
  const [formData, setFormData] = useState({
    // Basic Details
    product_type: "personal_loan_salaried",
    requested_amount: "",
    tenure_months: "12",
    
    // Applicant Details
    first_name: "",
    middle_name: "",
    last_name: "",
    father_name: "",
    mother_name: "",
    dob: "",
    gender: "",
    marital_status: "",
    pan_number: "",
    aadhaar_number: "",
    mobile: "",
    alternate_mobile: "",
    email: "",
    
    // Address
    current_address_line1: "",
    current_address_line2: "",
    current_city: "",
    current_state: "",
    current_pincode: "",
    residence_type: "",
    years_at_current_address: "",
    
    permanent_same_as_current: false,
    permanent_address_line1: "",
    permanent_address_line2: "",
    permanent_city: "",
    permanent_state: "",
    permanent_pincode: "",
    
    // Employment Details
    employer_name: "",
    employer_type: "",
    designation: "",
    department: "",
    official_email: "",
    date_of_joining: "",
    years_in_company: "",
    total_experience: "",
    gross_monthly_salary: "",
    net_monthly_salary: "",
    salary_mode: "",
    salary_bank_name: "",
    salary_account_number: "",
    
    // References
    reference1_name: "",
    reference1_email: "",
    reference1_phone: "",
    reference1_address: "",
    reference2_name: "",
    reference2_email: "",
    reference2_phone: "",
    reference2_address: "",
  });

  const updateField = (field: string, value: any) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const createApplicationMutation = useMutation({
    mutationFn: async () => {
      if (!orgId) throw new Error("No organization context");

      // Create application
      const { data: userData } = await supabase.auth.getUser();
      
      const { data: application, error: appError } = await supabase
        .from("loan_applications")
        .insert([{
          org_id: orgId!,
          application_number: "", // Will be auto-generated by trigger
          product_type: formData.product_type,
          requested_amount: parseFloat(formData.requested_amount),
          tenure_months: parseInt(formData.tenure_months),
          current_stage: "application_login",
          status: "in_progress",
          created_by: userData.user?.id || null,
        }])
        .select()
        .single();

      if (appError) throw appError;

      // Create applicant
      const currentAddress = {
        line1: formData.current_address_line1,
        line2: formData.current_address_line2,
        city: formData.current_city,
        state: formData.current_state,
        pincode: formData.current_pincode,
      };

      const permanentAddress = formData.permanent_same_as_current
        ? currentAddress
        : {
            line1: formData.permanent_address_line1,
            line2: formData.permanent_address_line2,
            city: formData.permanent_city,
            state: formData.permanent_state,
            pincode: formData.permanent_pincode,
          };

      const { data: applicant, error: applicantError } = await supabase
        .from("loan_applicants")
        .insert({
          loan_application_id: application.id,
          applicant_type: "primary",
          first_name: formData.first_name,
          middle_name: formData.middle_name || null,
          last_name: formData.last_name || null,
          father_name: formData.father_name || null,
          mother_name: formData.mother_name || null,
          dob: formData.dob,
          age: formData.dob
            ? new Date().getFullYear() - new Date(formData.dob).getFullYear()
            : null,
          gender: formData.gender,
          marital_status: formData.marital_status,
          pan_number: formData.pan_number,
          aadhaar_number: formData.aadhaar_number,
          mobile: formData.mobile,
          alternate_mobile: formData.alternate_mobile || null,
          email: formData.email || null,
          current_address: currentAddress,
          permanent_address: permanentAddress,
          residence_type: formData.residence_type,
          years_at_current_address: formData.years_at_current_address
            ? parseInt(formData.years_at_current_address)
            : null,
        })
        .select()
        .single();

      if (applicantError) throw applicantError;

      // Create employment details
      const { error: empError } = await supabase
        .from("loan_employment_details")
        .insert({
          applicant_id: applicant.id,
          employment_type: "salaried",
          employer_name: formData.employer_name,
          employer_type: formData.employer_type,
          designation: formData.designation,
          department: formData.department || null,
          official_email: formData.official_email || null,
          date_of_joining: formData.date_of_joining || null,
          years_in_company: formData.years_in_company
            ? parseFloat(formData.years_in_company)
            : null,
          total_experience: formData.total_experience
            ? parseFloat(formData.total_experience)
            : null,
          gross_monthly_salary: parseFloat(formData.gross_monthly_salary),
          net_monthly_salary: parseFloat(formData.net_monthly_salary),
          salary_mode: formData.salary_mode,
          salary_bank_name: formData.salary_bank_name || null,
          salary_account_number: formData.salary_account_number || null,
        });

      if (empError) throw empError;

      return application;
    },
    onSuccess: (application) => {
      queryClient.invalidateQueries({ queryKey: ["loan-applications"] });
      notify.success("Application Created", "Loan application created successfully");
      navigate(`/los/applications/${application.id}`);
    },
    onError: (error: Error) => {
      notify.error("Error", error.message);
    },
  });

  const handleSubmit = () => {
    // Basic validation
    if (!formData.requested_amount || parseFloat(formData.requested_amount) <= 0) {
      notify.error("Validation Error", "Please enter a valid loan amount");
      return;
    }

    if (!formData.first_name || !formData.dob || !formData.mobile) {
      notify.error("Validation Error", "Please fill all required applicant details");
      setCurrentTab("applicant");
      return;
    }

    if (!formData.employer_name || !formData.gross_monthly_salary) {
      notify.error("Validation Error", "Please fill all required employment details");
      setCurrentTab("employment");
      return;
    }

    createApplicationMutation.mutate();
  };

  const tabOrder = ["basic", "applicant", "address", "employment", "references"];
  const currentIndex = tabOrder.indexOf(currentTab);

  const goToNextTab = () => {
    if (currentIndex < tabOrder.length - 1) {
      setCurrentTab(tabOrder[currentIndex + 1]);
    }
  };

  const goToPreviousTab = () => {
    if (currentIndex > 0) {
      setCurrentTab(tabOrder[currentIndex - 1]);
    }
  };

  return (
    <DashboardLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Header */}
        <div>
          <Button
            variant="ghost"
            onClick={() => navigate("/los/applications")}
            className="mb-4"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Applications
          </Button>
          <h1 className="text-3xl font-bold text-foreground">New Loan Application</h1>
          <p className="text-muted-foreground mt-1">
            Personal Loan - Salaried
          </p>
        </div>

        <Tabs value={currentTab} onValueChange={setCurrentTab}>
          <TabsList className="grid w-full grid-cols-5">
            <TabsTrigger value="basic">Basic Details</TabsTrigger>
            <TabsTrigger value="applicant">Applicant</TabsTrigger>
            <TabsTrigger value="address">Address</TabsTrigger>
            <TabsTrigger value="employment">Employment</TabsTrigger>
            <TabsTrigger value="references">References</TabsTrigger>
          </TabsList>

          {/* Basic Details Tab */}
          <TabsContent value="basic">
            <Card>
              <CardHeader>
                <CardTitle>Loan Details</CardTitle>
                <CardDescription>
                  Enter the basic loan requirements
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="product_type">Product Type</Label>
                  <Select
                    value={formData.product_type}
                    onValueChange={(value) => updateField("product_type", value)}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="personal_loan_salaried">
                        Personal Loan - Salaried
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="requested_amount">Loan Amount *</Label>
                    <Input
                      id="requested_amount"
                      type="number"
                      placeholder="500000"
                      value={formData.requested_amount}
                      onChange={(e) => updateField("requested_amount", e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="tenure_months">Tenure (Months) *</Label>
                    <Select
                      value={formData.tenure_months}
                      onValueChange={(value) => updateField("tenure_months", value)}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {[12, 24, 36, 48, 60].map((months) => (
                          <SelectItem key={months} value={months.toString()}>
                            {months} months
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Applicant Details Tab */}
          <TabsContent value="applicant">
            <Card>
              <CardHeader>
                <CardTitle>Applicant Details</CardTitle>
                <CardDescription>
                  Enter personal information of the primary applicant
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid gap-4 md:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="first_name">First Name *</Label>
                    <Input
                      id="first_name"
                      value={formData.first_name}
                      onChange={(e) => updateField("first_name", e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="middle_name">Middle Name</Label>
                    <Input
                      id="middle_name"
                      value={formData.middle_name}
                      onChange={(e) => updateField("middle_name", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="last_name">Last Name</Label>
                    <Input
                      id="last_name"
                      value={formData.last_name}
                      onChange={(e) => updateField("last_name", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="father_name">Father's Name</Label>
                    <Input
                      id="father_name"
                      value={formData.father_name}
                      onChange={(e) => updateField("father_name", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="mother_name">Mother's Name</Label>
                    <Input
                      id="mother_name"
                      value={formData.mother_name}
                      onChange={(e) => updateField("mother_name", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="dob">Date of Birth *</Label>
                    <Input
                      id="dob"
                      type="date"
                      value={formData.dob}
                      onChange={(e) => updateField("dob", e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="gender">Gender</Label>
                    <Select
                      value={formData.gender}
                      onValueChange={(value) => updateField("gender", value)}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select gender" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="male">Male</SelectItem>
                        <SelectItem value="female">Female</SelectItem>
                        <SelectItem value="other">Other</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="marital_status">Marital Status</Label>
                    <Select
                      value={formData.marital_status}
                      onValueChange={(value) => updateField("marital_status", value)}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select status" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="single">Single</SelectItem>
                        <SelectItem value="married">Married</SelectItem>
                        <SelectItem value="divorced">Divorced</SelectItem>
                        <SelectItem value="widowed">Widowed</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="pan_number">PAN Number</Label>
                    <Input
                      id="pan_number"
                      value={formData.pan_number}
                      onChange={(e) => updateField("pan_number", e.target.value.toUpperCase())}
                      maxLength={10}
                      placeholder="ABCDE1234F"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="aadhaar_number">Aadhaar Number</Label>
                    <Input
                      id="aadhaar_number"
                      value={formData.aadhaar_number}
                      onChange={(e) => updateField("aadhaar_number", e.target.value)}
                      maxLength={12}
                      placeholder="xxxx xxxx xxxx"
                    />
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="mobile">Mobile Number *</Label>
                    <Input
                      id="mobile"
                      type="tel"
                      value={formData.mobile}
                      onChange={(e) => updateField("mobile", e.target.value)}
                      maxLength={10}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="alternate_mobile">Alternate Mobile</Label>
                    <Input
                      id="alternate_mobile"
                      type="tel"
                      value={formData.alternate_mobile}
                      onChange={(e) => updateField("alternate_mobile", e.target.value)}
                      maxLength={10}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="email">Email</Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email}
                      onChange={(e) => updateField("email", e.target.value)}
                    />
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* Address Tab */}
          <TabsContent value="address">
            <Card>
              <CardHeader>
                <CardTitle>Address Details</CardTitle>
                <CardDescription>
                  Enter current and permanent address
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-4">
                  <h3 className="font-semibold">Current Address</h3>
                  
                  <div className="space-y-2">
                    <Label htmlFor="current_address_line1">Address Line 1</Label>
                    <Input
                      id="current_address_line1"
                      value={formData.current_address_line1}
                      onChange={(e) => updateField("current_address_line1", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="current_address_line2">Address Line 2</Label>
                    <Input
                      id="current_address_line2"
                      value={formData.current_address_line2}
                      onChange={(e) => updateField("current_address_line2", e.target.value)}
                    />
                  </div>

                  <div className="grid gap-4 md:grid-cols-3">
                    <div className="space-y-2">
                      <Label htmlFor="current_city">City</Label>
                      <Input
                        id="current_city"
                        value={formData.current_city}
                        onChange={(e) => updateField("current_city", e.target.value)}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="current_state">State</Label>
                      <Input
                        id="current_state"
                        value={formData.current_state}
                        onChange={(e) => updateField("current_state", e.target.value)}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="current_pincode">Pincode</Label>
                      <Input
                        id="current_pincode"
                        value={formData.current_pincode}
                        onChange={(e) => updateField("current_pincode", e.target.value)}
                        maxLength={6}
                      />
                    </div>
                  </div>

                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="residence_type">Residence Type</Label>
                      <Select
                        value={formData.residence_type}
                        onValueChange={(value) => updateField("residence_type", value)}
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select type" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="owned">Owned</SelectItem>
                          <SelectItem value="rented">Rented</SelectItem>
                          <SelectItem value="company_provided">Company Provided</SelectItem>
                          <SelectItem value="parental">Parental</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="years_at_current_address">Years at Current Address</Label>
                      <Input
                        id="years_at_current_address"
                        type="number"
                        value={formData.years_at_current_address}
                        onChange={(e) => updateField("years_at_current_address", e.target.value)}
                      />
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    id="permanent_same_as_current"
                    checked={formData.permanent_same_as_current}
                    onChange={(e) => updateField("permanent_same_as_current", e.target.checked)}
                    className="h-4 w-4"
                  />
                  <Label htmlFor="permanent_same_as_current" className="cursor-pointer">
                    Permanent address is same as current address
                  </Label>
                </div>

                {!formData.permanent_same_as_current && (
                  <div className="space-y-4">
                    <h3 className="font-semibold">Permanent Address</h3>
                    
                    <div className="space-y-2">
                      <Label htmlFor="permanent_address_line1">Address Line 1</Label>
                      <Input
                        id="permanent_address_line1"
                        value={formData.permanent_address_line1}
                        onChange={(e) => updateField("permanent_address_line1", e.target.value)}
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="permanent_address_line2">Address Line 2</Label>
                      <Input
                        id="permanent_address_line2"
                        value={formData.permanent_address_line2}
                        onChange={(e) => updateField("permanent_address_line2", e.target.value)}
                      />
                    </div>

                    <div className="grid gap-4 md:grid-cols-3">
                      <div className="space-y-2">
                        <Label htmlFor="permanent_city">City</Label>
                        <Input
                          id="permanent_city"
                          value={formData.permanent_city}
                          onChange={(e) => updateField("permanent_city", e.target.value)}
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="permanent_state">State</Label>
                        <Input
                          id="permanent_state"
                          value={formData.permanent_state}
                          onChange={(e) => updateField("permanent_state", e.target.value)}
                        />
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="permanent_pincode">Pincode</Label>
                        <Input
                          id="permanent_pincode"
                          value={formData.permanent_pincode}
                          onChange={(e) => updateField("permanent_pincode", e.target.value)}
                          maxLength={6}
                        />
                      </div>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          {/* Employment Tab */}
          <TabsContent value="employment">
            <Card>
              <CardHeader>
                <CardTitle>Employment Details</CardTitle>
                <CardDescription>
                  Enter employment and income information
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="employer_name">Employer Name *</Label>
                    <Input
                      id="employer_name"
                      value={formData.employer_name}
                      onChange={(e) => updateField("employer_name", e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="employer_type">Employer Type</Label>
                    <Select
                      value={formData.employer_type}
                      onValueChange={(value) => updateField("employer_type", value)}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="private">Private</SelectItem>
                        <SelectItem value="government">Government</SelectItem>
                        <SelectItem value="psu">PSU</SelectItem>
                        <SelectItem value="mnc">MNC</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="designation">Designation</Label>
                    <Input
                      id="designation"
                      value={formData.designation}
                      onChange={(e) => updateField("designation", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="department">Department</Label>
                    <Input
                      id="department"
                      value={formData.department}
                      onChange={(e) => updateField("department", e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="official_email">Official Email</Label>
                  <Input
                    id="official_email"
                    type="email"
                    value={formData.official_email}
                    onChange={(e) => updateField("official_email", e.target.value)}
                  />
                </div>

                <div className="grid gap-4 md:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="date_of_joining">Date of Joining</Label>
                    <Input
                      id="date_of_joining"
                      type="date"
                      value={formData.date_of_joining}
                      onChange={(e) => updateField("date_of_joining", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="years_in_company">Years in Company</Label>
                    <Input
                      id="years_in_company"
                      type="number"
                      step="0.1"
                      value={formData.years_in_company}
                      onChange={(e) => updateField("years_in_company", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="total_experience">Total Experience (Years)</Label>
                    <Input
                      id="total_experience"
                      type="number"
                      step="0.1"
                      value={formData.total_experience}
                      onChange={(e) => updateField("total_experience", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                  <div className="space-y-2">
                    <Label htmlFor="gross_monthly_salary">Gross Monthly Salary *</Label>
                    <Input
                      id="gross_monthly_salary"
                      type="number"
                      value={formData.gross_monthly_salary}
                      onChange={(e) => updateField("gross_monthly_salary", e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="net_monthly_salary">Net Monthly Salary *</Label>
                    <Input
                      id="net_monthly_salary"
                      type="number"
                      value={formData.net_monthly_salary}
                      onChange={(e) => updateField("net_monthly_salary", e.target.value)}
                      required
                    />
                  </div>
                </div>

                <div className="grid gap-4 md:grid-cols-3">
                  <div className="space-y-2">
                    <Label htmlFor="salary_mode">Salary Mode</Label>
                    <Select
                      value={formData.salary_mode}
                      onValueChange={(value) => updateField("salary_mode", value)}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select mode" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="bank_transfer">Bank Transfer</SelectItem>
                        <SelectItem value="cash">Cash</SelectItem>
                        <SelectItem value="cheque">Cheque</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="salary_bank_name">Salary Bank Name</Label>
                    <Input
                      id="salary_bank_name"
                      value={formData.salary_bank_name}
                      onChange={(e) => updateField("salary_bank_name", e.target.value)}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="salary_account_number">Account Number</Label>
                    <Input
                      id="salary_account_number"
                      value={formData.salary_account_number}
                      onChange={(e) => updateField("salary_account_number", e.target.value)}
                    />
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          {/* References Tab */}
          <TabsContent value="references">
            <Card>
              <CardHeader>
                <CardTitle>References</CardTitle>
                <CardDescription>
                  Provide two personal or professional references
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Reference 1 */}
                <div className="space-y-4">
                  <h3 className="font-semibold">Reference 1</h3>
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="reference1_name">Name *</Label>
                      <Input
                        id="reference1_name"
                        value={formData.reference1_name}
                        onChange={(e) => updateField("reference1_name", e.target.value)}
                        placeholder="Full name"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="reference1_phone">Phone *</Label>
                      <Input
                        id="reference1_phone"
                        type="tel"
                        value={formData.reference1_phone}
                        onChange={(e) => updateField("reference1_phone", e.target.value)}
                        maxLength={10}
                        placeholder="Mobile number"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="reference1_email">Email</Label>
                    <Input
                      id="reference1_email"
                      type="email"
                      value={formData.reference1_email}
                      onChange={(e) => updateField("reference1_email", e.target.value)}
                      placeholder="Email address"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="reference1_address">Address</Label>
                    <Input
                      id="reference1_address"
                      value={formData.reference1_address}
                      onChange={(e) => updateField("reference1_address", e.target.value)}
                      placeholder="Full address"
                    />
                  </div>
                </div>

                {/* Reference 2 */}
                <div className="space-y-4">
                  <h3 className="font-semibold">Reference 2</h3>
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2">
                      <Label htmlFor="reference2_name">Name *</Label>
                      <Input
                        id="reference2_name"
                        value={formData.reference2_name}
                        onChange={(e) => updateField("reference2_name", e.target.value)}
                        placeholder="Full name"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="reference2_phone">Phone *</Label>
                      <Input
                        id="reference2_phone"
                        type="tel"
                        value={formData.reference2_phone}
                        onChange={(e) => updateField("reference2_phone", e.target.value)}
                        maxLength={10}
                        placeholder="Mobile number"
                      />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="reference2_email">Email</Label>
                    <Input
                      id="reference2_email"
                      type="email"
                      value={formData.reference2_email}
                      onChange={(e) => updateField("reference2_email", e.target.value)}
                      placeholder="Email address"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="reference2_address">Address</Label>
                    <Input
                      id="reference2_address"
                      value={formData.reference2_address}
                      onChange={(e) => updateField("reference2_address", e.target.value)}
                      placeholder="Full address"
                    />
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        {/* Navigation Buttons */}
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <Button
                variant="outline"
                onClick={goToPreviousTab}
                disabled={currentIndex === 0}
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Previous
              </Button>

              {currentIndex === tabOrder.length - 1 ? (
                <Button
                  onClick={handleSubmit}
                  disabled={createApplicationMutation.isPending}
                >
                  <Save className="mr-2 h-4 w-4" />
                  Create Application
                </Button>
              ) : (
                <Button onClick={goToNextTab}>
                  Next
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              )}
            </div>
          </CardContent>
        </Card>
      </div>
    </DashboardLayout>
  );
}
